name: Gherking extractor for GitHub Issues
description:
  'GitHub Action that processes Gherkin content from issues and turn them into a
  content that can be then saved into a file'
author: 'Government of British Columbia Natual Resources'
branding:
  icon: check-square
  color: blue

inputs:
  ### Required
  issue:
    description: The issue number
    required: true

  ### Typical / recommended
  default_title:
    description:
      A default title for the issue, to check if the user has changed it
  update_title:
    description:
      Defines if the issue title should be updated in case it is not different
      from the default one
    default: 'false'

  ### Usually a bad idea / not recommended
  token:
    description: Your GitHub token or a personal access token
    default: ${{ github.token }}
  owner:
    description: The owner of the repository
    default: ${{ github.repository_owner }}
  repo:
    description: The repository name
    default: ${{ github.repository }}

# Define your outputs here.
outputs:
  title:
    description:
      The title of the issue. Usually the original title, unless it was updated
  sanitized_title:
    description:
      The title of the issue in a clean and sanitized format that can be used as
      a file name
  body:
    description: The original body of the issue
  feature:
    description: The feature content

runs:
  using: node20
  main: dist/index.js
