name: Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Action Test
    uses: ./.github/workflows/reusable-tests.yml

  publish:
    name: Publish
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v5
        id: changelog
        with:
          github-token: ${{ github.token }}
          output-file: 'CHANGELOG.md'
          skip-version-file: 'true'
          skip-commit: 'true'
          git-push: 'true'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.tag != '' }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
